package com.mycompany.blog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LayoutAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLayoutAllPropertiesEquals(Layout expected, Layout actual) {
        assertLayoutAutoGeneratedPropertiesEquals(expected, actual);
        assertLayoutAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLayoutAllUpdatablePropertiesEquals(Layout expected, Layout actual) {
        assertLayoutUpdatableFieldsEquals(expected, actual);
        assertLayoutUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLayoutAutoGeneratedPropertiesEquals(Layout expected, Layout actual) {
        assertThat(actual)
            .as("Verify Layout auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLayoutUpdatableFieldsEquals(Layout expected, Layout actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLayoutUpdatableRelationshipsEquals(Layout expected, Layout actual) {
        // empty method
    }
}
